openapi: 3.0.1
info:
  contact:
    email: dtslubbersen@gmail.com
    name: Declan Lubbersen
    url: https://github.com/dtslubbersen/go-quiz
  description: "This is the API documentation for go-quiz, a simple Quiz API allowing\
    \ users to obtain quizzes, answer the questions and see their results compared\
    \ to other users."
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: go-quiz
  version: "1.0"
servers:
- url: //localhost:8080/api/v1
paths:
  /auth/token:
    post:
      description: Creates a JWT token for a user after validating their credentials
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/api.CreateTokenPayload'
        description: User credentials
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_auth_token_post_201_response'
          description: Created
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_auth_token_post_400_response'
          description: Bad Request
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_auth_token_post_400_response'
          description: Unauthorized
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_auth_token_post_400_response'
          description: Internal Server Error
      summary: Generates an authentication token
      tags:
      - auth
      x-codegen-request-body-name: payload
  /quizzes:
    get:
      description: Fetches a list of all quizzes from the in memory store
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_quizzes_get_200_response'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_auth_token_post_400_response'
          description: Bad Request
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_auth_token_post_400_response'
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Retrieves all quizzes
      tags:
      - quizzes
  /quizzes/{quizId}:
    get:
      description: Fetches a specific quiz using its ID from the in-memory store
      parameters:
      - description: Quiz ID
        in: path
        name: quizId
        required: true
        schema:
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_quizzes__quizId__get_200_response'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_auth_token_post_400_response'
          description: Bad Request
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_auth_token_post_400_response'
          description: Not Found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_auth_token_post_400_response'
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Retrieves a quiz by ID
      tags:
      - quizzes
  /quizzes/{quizId}/results:
    get:
      description: Fetches the result of a quiz attempt by the current user.
      parameters:
      - description: Quiz ID
        in: path
        name: quizId
        required: true
        schema:
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_quizzes__quizId__results_get_200_response'
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_auth_token_post_400_response'
          description: Bad Request
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_auth_token_post_400_response'
          description: Not Found
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_auth_token_post_400_response'
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Retrieves quiz results for a user
      tags:
      - quizzes
  /quizzes/{quizId}/submit:
    post:
      description: Allows a user to submit answers for a given quiz
      parameters:
      - description: Quiz ID
        in: path
        name: quizId
        required: true
        schema:
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/api.SubmitQuizAnswersPayload'
        description: User's answers
        required: true
      responses:
        "200":
          content: {}
          description: OK
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_auth_token_post_400_response'
          description: Bad Request
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_auth_token_post_400_response'
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Submits answers for a quiz
      tags:
      - quizzes
      x-codegen-request-body-name: payload
components:
  schemas:
    api.CreateTokenPayload:
      properties:
        email:
          example: demo@quiz.com
          maxLength: 256
          type: string
        password:
          example: password
          maxLength: 64
          minLength: 8
          type: string
      required:
      - email
      - password
      type: object
    api.Response:
      properties:
        data:
          type: object
        error:
          type: string
      type: object
    api.SubmitQuizAnswersPayload:
      properties:
        answers:
          items:
            $ref: '#/components/schemas/api_SubmitQuizAnswersPayload_answers_inner'
          type: array
      required:
      - answers
      type: object
    api.TokenCreatedResponse:
      example:
        expires_in: 0
        user:
          id: 6
          email: email
        token: token
      properties:
        expires_in:
          type: integer
        token:
          type: string
        user:
          $ref: '#/components/schemas/api.UserResponse'
      type: object
    api.UserResponse:
      example:
        id: 6
        email: email
      properties:
        email:
          type: string
        id:
          type: integer
      type: object
    store.Question:
      example:
        quiz_id: 5
        answers:
        - answers
        - answers
        correct_answer_index: 6
        id: 1
        value: value
      properties:
        answers:
          items:
            type: string
          type: array
        correct_answer_index:
          type: integer
        id:
          type: integer
        quiz_id:
          type: integer
        value:
          type: string
      type: object
    store.Quiz:
      example:
        questions:
        - quiz_id: 5
          answers:
          - answers
          - answers
          correct_answer_index: 6
          id: 1
          value: value
        - quiz_id: 5
          answers:
          - answers
          - answers
          correct_answer_index: 6
          id: 1
          value: value
        description: description
        id: 0
        title: title
      properties:
        description:
          type: string
        id:
          type: integer
        questions:
          items:
            $ref: '#/components/schemas/store.Question'
          type: array
        title:
          type: string
      type: object
    store.Result:
      example:
        question_count: 6
        quiz_id: 1
        user_percentile: 5
        user_id: 5
        user_score: 2
        id: 0
      properties:
        id:
          type: integer
        question_count:
          type: integer
        quiz_id:
          type: integer
        user_id:
          type: integer
        user_percentile:
          type: integer
        user_score:
          type: integer
      type: object
    _auth_token_post_201_response:
      allOf:
      - $ref: '#/components/schemas/api.Response'
      - properties:
          data:
            $ref: '#/components/schemas/api.TokenCreatedResponse'
        type: object
      example:
        data:
          expires_in: 0
          user:
            id: 6
            email: email
          token: token
        error: error
    _auth_token_post_400_response:
      allOf:
      - $ref: '#/components/schemas/api.Response'
      - properties:
          error:
            type: string
        type: object
      example:
        data: "{}"
        error: error
    _quizzes_get_200_response:
      allOf:
      - $ref: '#/components/schemas/api.Response'
      - properties:
          data:
            items:
              $ref: '#/components/schemas/store.Quiz'
            type: array
        type: object
      example:
        data:
        - questions:
          - quiz_id: 5
            answers:
            - answers
            - answers
            correct_answer_index: 6
            id: 1
            value: value
          - quiz_id: 5
            answers:
            - answers
            - answers
            correct_answer_index: 6
            id: 1
            value: value
          description: description
          id: 0
          title: title
        - questions:
          - quiz_id: 5
            answers:
            - answers
            - answers
            correct_answer_index: 6
            id: 1
            value: value
          - quiz_id: 5
            answers:
            - answers
            - answers
            correct_answer_index: 6
            id: 1
            value: value
          description: description
          id: 0
          title: title
        error: error
    _quizzes__quizId__get_200_response:
      allOf:
      - $ref: '#/components/schemas/api.Response'
      - properties:
          data:
            $ref: '#/components/schemas/store.Quiz'
        type: object
      example:
        data:
          questions:
          - quiz_id: 5
            answers:
            - answers
            - answers
            correct_answer_index: 6
            id: 1
            value: value
          - quiz_id: 5
            answers:
            - answers
            - answers
            correct_answer_index: 6
            id: 1
            value: value
          description: description
          id: 0
          title: title
        error: error
    _quizzes__quizId__results_get_200_response:
      allOf:
      - $ref: '#/components/schemas/api.Response'
      - properties:
          data:
            $ref: '#/components/schemas/store.Result'
        type: object
      example:
        data:
          question_count: 6
          quiz_id: 1
          user_percentile: 5
          user_id: 5
          user_score: 2
          id: 0
        error: error
    api_SubmitQuizAnswersPayload_answers_inner:
      properties:
        answer_index:
          type: integer
        question_id:
          type: integer
      required:
      - answer_index
      - question_id
      type: object
  securitySchemes:
    BearerAuth:
      description: "Use a 'Bearer {token}' to authenticate your requests"
      in: header
      name: Authorization
      type: apiKey
x-original-swagger-version: "2.0"
